language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: modasser
  password:
    secure: CthHm27DWnbv9t2Jn9+gqHWvXom/WywztPOuuin5GJj6R/fT66T0jBU8x6XIsKDqXFGZEPa2HhlvbH+pey9WkTwwu8E8ceDL94h7s1ZzH2hT/n5DoZ4cFYeI37P/IFTc60QnlEpod3X+igSqwmqbaBCq7OXY/EcMt1HcWKEKazBOZgns5/x/xRaJF8R17q3FQbQtjHg4nHrotStdxFJrBdkz24qKn/WLcmK1g2GdqP70O6uh7Wo2XhCS+60tYAcbD5ECbGLJfEwFylGALLveKNTTGqx4Qt5OaGshMXrZ1s5YC0FLkiwFEHzQl+yhMEa04/57Ef9ineQAQmLoEcCC3+rOysTjcZ1e0bzTQ+K5q8gg04Cex93oGqx16g5u3MrEt326Tjy0jKDluVvkibTmnMYbzEmgn8Y2lrzt4vq5mZl0bdRJm9TBHHHi7jfIOh2TUQ1lgQ3f6ByM08CLBvm1qn3bdbxS9Aqufl6LQfhFY7N3gzjEgT2CMP0l787waDlfl2Nx752Mx2i0qcJGRjpa8lAFNJAa6ZyKQAVbB9LScudVcZS/bGSNPm3+C/qhpZlQ4SwWmOKLjMXxOCDjj+I2SCuBE4ZcvbgWdA2IbAKEqK5L2dt1T+/ikGAbxmr28QR43hrVdHoRUkMPV+a2bWqT7y9jUU0RXNI1CHIo4NxSQt8=
  on:
    tags: true
    repo: modasserbillah/plot_coverage
    python: 3.8
dd:
  secure: do+I0yMnjbbNCWNybkMoia+IIz5EKtqUR8h/sN14vykk/31A+ILCiM7jS81K6/LJkWNHyp9AWpVSs35qzmj900BtW96U63LHXhq3cR1h2aihB0KSVp+XtVs6dNutAdQ8yT+C/mv5qY0kcMq09lPKMUdylNaOblJYwl4+n6vIqnNvA17qAUJrj396hiqVCy+v/cOpTzElNntkn5fV8BKOJPqsMdpSLsyXnlYnPzda8MbgSB3YJrVAPVR/eN8Tgz5ZzBqG7e5V/zEUdv01XMNgyVv44XUfxxle6CQIZpirtQur3ad0/ZBBgm+PNxqj/Z/qCRoZg78UyPDQvc7FHTgtpVL+jgJp/l0cvOUxCAfaL/STihSxWWWJ+iXD2IDfRqVcFQZVZYilSTjNKzjHjBWg8K8ZD/EQClvMFokiTyHBD7Ai6JmtvhiIZo43lGpzYHtgQWG47bjNtiZm5kYTrc4lZzaDxWHL6FLWeAqDGfcCTGHaSLTB+o8U3z/hxRSTUrKoLzZzbVWcQfzRoHYaaVALIKw/UzdtD1/R3QDnLB4E9lyQhubACQN5S09yvKlVQThkU0sV8RDG73V4KAlowsd4cE3NcArGmlmGvPP9Uh10uDk4IDUDJVE3TYwxD9nA4YdA9jrn8A6Lm9uZyzJNhxcbb2EP5gPxugnWqvqxzO+9zbA=
